### ISSUE TITLE
Add support for icon destination path

### ISSUE THREAD

**Issue by alainlecluse** [easthing/pwa-manifest-webpack-plugin#3]
it would be very nice if it was possible to configure a sub folder for the generated icons.

**Comment by easthing** [comment]
no need to generate sub  folder in webpack

**Comment by kesne** [comment]
Having this feature would be super useful! 

@easthing Webpack can do subfolders by passing something like `/folderName` to the generated name. This is especially useful if you use webpack to build multiple asset types and you want them to end up in folders based on their type. In our case, these folders are based on how we cache different assets (e.g. image assets can be cached forever, js/css assets get invalidated quickly).

**Comment by easthing** [comment]
Ok, so I'll be up to date
