### ISSUE TITLE
Error installing with NPM

### ISSUE THREAD

**Issue by Stegosource** [easthing/pwa-manifest-webpack-plugin#4]
Hi, I tried installing this module with npm i pwa-manifest-webpack-plugin --save

I got the following error: 

2198 error Windows_NT 10.0.14393
2199 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "pwa-manifest-webpack-plugin" "--save"
2200 error node v6.3.1
2201 error npm  v3.10.3
2202 error code ELIFECYCLE
2203 error lwip@0.0.9 install: `node-gyp rebuild`
2203 error Exit status 1
2204 error Failed at the lwip@0.0.9 install script 'node-gyp rebuild'.
2204 error Make sure you have the latest version of node.js and npm installed.
2204 error If you do, this is most likely a problem with the lwip package,
2204 error not with npm itself.
2204 error Tell the author that this fails on your system:
2204 error     node-gyp rebuild
2204 error You can get information on how to open an issue for this project with:
2204 error     npm bugs lwip
2204 error Or if that isn't available, you can get their info via:
2204 error     npm owner ls lwip
2204 error There is likely additional logging output above.
2205 verbose exit [ 1, true ]

I think this is an issue with the lwip module, but was wondering if you have come across a solution for this?

**Comment by M-Hc0d3** [comment]
Any updates?

**Comment by Stegosource** [comment]
Yeah, it was also an issue working on Windows. I also have bash installed on Windows so doing everything through there and bumping my node version back down seems to have solved it.

More details here: https://github.com/charlesBochet/vueJSPwa/issues/2#issuecomment-299414204

**Comment by M-Hc0d3** [comment]
Cheers bro

**Comment by M-Hc0d3** [comment]
Btw what version did you bump it down to?

**Comment by Shubham-Sinha** [comment]
Worked on 5.6

**Comment by wyqydsyq** [comment]
https://github.com/easthing/pwa-manifest-webpack-plugin/issues/5
https://github.com/EyalAr/lwip/issues/297

Issue is caused by a bug in a library (`lwip`) that this package depends on. 

@easthing someone in the issue thread on `lwip` suggested using this library instead which allows you to process images without any statically compiled binaries:
https://www.npmjs.com/package/jimp

Might be worth changing this plugin to use that as it should make it a lot more portable.

**Comment by easthing** [comment]
fixed thinks @wyqydsyq
